# Generated by Django 5.2.3 on 2025-06-17 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinasiWisata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, verbose_name='Nama Destinasi')),
                ('deskripsi', models.TextField(verbose_name='Deskripsi')),
                ('lokasi', models.CharField(max_length=255, verbose_name='Lokasi')),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Dibuat')),
                ('tanggal_diperbarui', models.DateTimeField(auto_now=True, verbose_name='Tanggal Diperbarui')),
            ],
            options={
                'verbose_name': 'Destinasi Wisata',
                'verbose_name_plural': 'Destinasi Wisata',
            },
        ),
        migrations.CreateModel(
            name='KategoriDestinasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama Kategori')),
                ('deskripsi', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
            ],
            options={
                'verbose_name': 'Kategori Destinasi',
                'verbose_name_plural': 'Kategori Destinasi',
            },
        ),
        migrations.CreateModel(
            name='GambarDestinasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar', models.ImageField(upload_to='gambar_destinasi/', verbose_name='Gambar')),
                ('keterangan', models.CharField(blank=True, max_length=255, verbose_name='Keterangan')),
                ('destinasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gambar', to='wisata.destinasiwisata', verbose_name='Destinasi')),
            ],
            options={
                'verbose_name': 'Gambar Destinasi',
                'verbose_name_plural': 'Gambar Destinasi',
            },
        ),
        migrations.AddField(
            model_name='destinasiwisata',
            name='kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinasi', to='wisata.kategoridestinasi', verbose_name='Kategori'),
        ),
        migrations.CreateModel(
            name='UlasanPengguna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(verbose_name='Rating (1-5)')),
                ('komentar', models.TextField(blank=True, verbose_name='Komentar')),
                ('tanggal_ulasan', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Ulasan')),
                ('destinasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ulasan', to='wisata.destinasiwisata', verbose_name='Destinasi')),
                ('pengguna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Pengguna')),
            ],
            options={
                'verbose_name': 'Ulasan Pengguna',
                'verbose_name_plural': 'Ulasan Pengguna',
                'ordering': ['-tanggal_ulasan'],
            },
        ),
    ]
