# Generated by Django 5.2.3 on 2025-07-04 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wisata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destinasiwisata',
            options={},
        ),
        migrations.AddField(
            model_name='destinasiwisata',
            name='harga_tiket',
            field=models.CharField(default='Gratis', max_length=50),
        ),
        migrations.AddField(
            model_name='destinasiwisata',
            name='jam_buka',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destinasiwisata',
            name='jam_tutup',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='destinasiwisata',
            name='deskripsi',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='destinasiwisata',
            name='kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wisata.kategoridestinasi'),
        ),
        migrations.AlterField(
            model_name='destinasiwisata',
            name='lokasi',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='destinasiwisata',
            name='nama',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='destinasiwisata',
            name='tanggal_dibuat',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='destinasiwisata',
            name='tanggal_diperbarui',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='gambardestinasi',
            name='destinasi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gambar', to='wisata.destinasiwisata'),
        ),
    ]
