# Generated by Django 5.2.3 on 2025-07-04 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wisata', '0002_alter_destinasiwisata_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailHargaTiket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_tiket', models.CharField(choices=[('masuk_lokal', 'Tiket Masuk Turis Lokal'), ('masuk_asing', 'Tiket Masuk Turis Asing'), ('parkir_motor', 'Parkir Motor'), ('parkir_mobil', 'Parkir Mobil'), ('parkir_bus', 'Parkir Bus'), ('wahana', 'Wahana Tambahan'), ('guide', 'Guide/Pemandu'), ('other', 'Lainnya')], max_length=20, verbose_name='Jenis Tiket')),
                ('nama_tiket', models.CharField(help_text='Contoh: Tiket Masuk Pantai Gigi Hiu', max_length=100, verbose_name='Nama Tiket')),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Harga (Rp)')),
                ('satuan', models.CharField(default='orang', help_text='Contoh: orang, motor, mobil, group', max_length=50, verbose_name='Satuan')),
                ('keterangan', models.TextField(blank=True, null=True, verbose_name='Keterangan Tambahan')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('urutan', models.PositiveSmallIntegerField(default=1, verbose_name='Urutan Tampil')),
                ('destinasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_harga', to='wisata.destinasiwisata', verbose_name='Destinasi')),
            ],
            options={
                'verbose_name': 'Detail Harga Tiket',
                'verbose_name_plural': 'Detail Harga Tiket',
                'ordering': ['urutan', 'jenis_tiket'],
                'unique_together': {('destinasi', 'jenis_tiket', 'nama_tiket')},
            },
        ),
    ]
